sudo : required
services:
        - docker

before_install:
        - docker build -t sachipat/react-my-app -f Dockerfile.dev .

script:
        docker run -e CI=true -it sachipat/react-my-app npm rum test
